# Generated by Django 4.2.7 on 2023-11-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_ru', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.type'),
        ),
    ]
