# Generated by Django 4.2.7 on 2023-11-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_type_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recall',
            field=models.ManyToManyField(blank=True, null=True, to='Menu.review'),
        ),
    ]
