# Generated by Django 4.2.7 on 2023-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_alter_menu_recall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='recall',
            field=models.ManyToManyField(blank=True, null=True, to='Menu.review'),
        ),
    ]
