# Generated by Django 4.1.3 on 2023-11-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_alter_menu_recall'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='media/product/default.png', upload_to='media/product'),
        ),
    ]
