# Generated by Django 4.2.7 on 2023-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_remove_application_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabel_number', models.IntegerField()),
            ],
        ),
    ]
