# Generated by Django 4.2.7 on 2023-11-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0007_alter_menu_recall'),
        ('Application', '0007_alter_application_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=500)),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.basket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
