# Generated by Django 4.2.7 on 2023-11-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_alter_menu_recall'),
        ('Application', '0008_application_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.basket')),
            ],
        ),
    ]
