# Generated by Django 4.2.7 on 2023-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_number_alter_user_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nnn'),
        ),
    ]
