# Generated by Django 4.2.7 on 2023-11-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories_vote',
            name='vote',
            field=models.ManyToManyField(to='storis.vote'),
        ),
        migrations.AlterField(
            model_name='stories_vote_img',
            name='vote_img',
            field=models.ImageField(upload_to='media/stories/vote'),
        ),
    ]
