# Generated by Django 4.2.7 on 2023-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
