# Generated by Django 4.2.7 on 2023-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_menu_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
