# Generated by Django 4.2.7 on 2023-11-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_menu_comment_alter_menu_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='review',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='speed',
        ),
        migrations.AddField(
            model_name='menu',
            name='Review',
            field=models.ManyToManyField(to='Menu.review'),
        ),
    ]
