# Generated by Django 4.2.7 on 2023-11-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_review_remove_menu_comment_remove_menu_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baskets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat', models.ManyToManyField(to='Menu.menu')),
            ],
        ),
    ]
