# Generated by Django 4.2.7 on 2023-11-22 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0005_baskets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to=settings.AUTH_USER_MODEL)),
                ('eat', models.ManyToManyField(to='Menu.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Baskets',
        ),
    ]
