# Generated by Django 4.2.7 on 2023-11-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_basket_delete_baskets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Name',
            new_name='name',
        ),
    ]
