# Generated by Django 4.2.7 on 2023-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_rename_name_basket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
