# Generated by Django 4.2.7 on 2023-11-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_alter_basket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='Review',
            field=models.ManyToManyField(blank=True, null=True, to='Menu.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.grade'),
        ),
    ]
