# Generated by Django 4.2.7 on 2023-11-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0015_reviewthrough_alter_menu_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')], default=0),
        ),
    ]
