# Generated by Django 4.2.7 on 2023-11-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0016_alter_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='Review',
        ),
    ]
