# Generated by Django 4.2.7 on 2023-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0017_rename_review_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Review',
            field=models.ManyToManyField(blank=True, null=True, through='Menu.reviewThrough', to='Menu.review'),
        ),
    ]
