# Generated by Django 4.2.7 on 2023-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0018_alter_menu_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Связь оценки блюда и блюда', 'verbose_name_plural': 'Связи оценок блюд и блюд'},
        ),
        migrations.AlterModelOptions(
            name='reviewthrough',
            options={},
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='speed',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Review',
            field=models.ManyToManyField(through='Menu.reviewThrough', to='Menu.review'),
        ),
    ]
