# Generated by Django 4.2.7 on 2023-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0019_alter_menu_options_alter_reviewthrough_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='reviewthrough',
            options={'verbose_name': 'Связь оценки блюда и блюда', 'verbose_name_plural': 'Связи оценок блюд и блюд'},
        ),
        migrations.RenameField(
            model_name='reviewthrough',
            old_name='asntement',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='reviewthrough',
            old_name='dish',
            new_name='reView',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
