# Generated by Django 4.2.7 on 2023-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0020_alter_menu_options_alter_reviewthrough_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Review',
            field=models.ManyToManyField(to='Menu.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Review',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='reviewThrough',
        ),
    ]
