# Generated by Django 4.2.7 on 2023-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0021_review_speed_alter_menu_review_alter_review_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
